{
 "title": "Starlink Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB DataSource", "query": "starlinkstats" },
   {
    "name": "DISH_ID",
    "label": "Dish ID:",
    "query": "from(bucket: \"${DS_INFLUXDB}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> distinct(column: \"id\")"
   },
   {
    "name": "STATS_FUNCTION",
    "label": "Stats Function",
    "query": "mean,max, p95 : (tables=<-\\, column) => tables |> quantile(q: 0.95\\, method: \"exact_selector\")"
   },
   {
    "name": "SPAN",
    "label": "Span",
    "query": "auto : v.windowPeriod, 1s, 10s, 1m, 5m"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${DS_INFLUXDB}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> last()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"_start\", \"_stop\", \"_time\", \"_measurement\", \"id\"])"
    }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"state\")\n  |> map(fn:(r) => ({\n     r with\n     _field: r._value,\n     _value: 1\n  }))\n  |> aggregateWindow(every: ${SPAN}, fn: count, createEmpty: false)\n  |> map(fn:(r) => ({\n     r with\n     _value: if r._value >= 1 then 1 else 0\n  }))\n  |> drop(columns: [\"id\"])\n//https://community.influxdata.com/t/rename-value-using-pivot-rename-un-pivot/12757/6"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_INFLUXDB}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.history\")\n  |> filter(fn: (r) => r[\"_field\"] == \"downlink_throughput_bps\" or r[\"_field\"] == \"uplink_throughput_bps\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> aggregateWindow(every: ${SPAN}, fn: ${STATS_FUNCTION}, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Latency & Drop Percertage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_INFLUXDB}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.history\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pop_ping_latency_ms\" or r[\"_field\"] == \"pop_ping_drop_rate\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> aggregateWindow(every: ${SPAN}, fn: ${STATS_FUNCTION}, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"${DS_INFLUXDB}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_mast_not_near_vertical\" or r[\"_field\"] == \"alert_motors_stuck\" or r[\"_field\"] == \"alert_roaming\" or r[\"_field\"] == \"alert_slow_ethernet_speeds\" or r[\"_field\"] == \"alert_thermal_shutdown\" or r[\"_field\"] == \"alert_thermal_throttle\" or r[\"_field\"] == \"alert_unexpected_location\")\n  |> toInt()\n  |> aggregateWindow(every: ${SPAN}, fn: max, createEmpty: false)\n  |> toBool()\n  |> drop(columns: [\"id\"])"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fraction_obstructed\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> aggregateWindow(every: ${SPAN}, fn: ${STATS_FUNCTION}, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"currently_obstructed\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> toInt()\n  |> aggregateWindow(every: ${SPAN}, fn: ${STATS_FUNCTION}, createEmpty: false)\n  |> toBool()"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"obstruction_interval\" or r[\"_field\"] == \"obstruction_duration\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> aggregateWindow(every: ${SPAN}, fn: ${STATS_FUNCTION}, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\n  |> filter(fn: (r) => r[\"id\"] == \"${DISH_ID}\")\n  |> toInt()\n  |> aggregateWindow(every: ${SPAN}, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"starlinkstats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spacex.starlink.user_terminal.status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"software_version\")\n  |> map(fn:(r) => ({\n     r with\n     _field: r._value,\n     _value: 1\n  }))\n  |> aggregateWindow(every: ${SPAN}, fn: count, createEmpty: false)\n  |> map(fn:(r) => ({\n     r with\n     _value: if r._value >= 1 then 1 else 0\n  }))\n  |> drop(columns: [\"id\"])"
    }
   ]
  }
 ]
}